#!/usr/bin/env python3
"""Build distinct SPARCALViewer studies for the P4/P6 CalicoST ablation.

Each P4/P6 replicate receives two somatic-call studies: full_calicost uses
informative purity, spatial and clone-resolved CNV evidence; while
spatial_only_no_calicost removes purity, clone, CNV, and purity-spatial proxy
features. Names, source matrices, folders, and archives are disjoint.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import shutil
import sys
import zipfile
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd
from scipy.io import mmread


PROJECT_ROOT = Path("/data/maiziezhou_lab/leiy4/snv_calling")
VIEWER_ROOT = Path("/data/maiziezhou_lab/leiy4/SPARCAL_Benchmarking/viewer")
STMUT_ROOT = Path(
    "/lfs/archer.accre.vu/maiziezhou_lab/maiziezhou_lab/"
    "Datasets/ST_datasets/STmut_Data"
)
MODES = {
    "full_calicost": {
        "model": "SPARCAL_full_calicost",
        "description": (
            "Full SPARCAL somatic calls using every informative CalicoST purity/CNV "
            "feature available for this section."
        ),
    },
    "spatial_only_no_calicost": {
        "model": "SPARCAL_ablation_no_calicost",
        "description": (
            "Ablation SPARCAL somatic calls using spatial clustering only; tumor "
            "purity, clone labels, CNV consistency, and their interaction are absent."
        ),
    },
}
SAMPLES = (("P4", "1"), ("P4", "2"), ("P6", "1"), ("P6", "2"))
POSITION_COLUMNS = [
    "barcode", "in_tissue", "array_row", "array_col",
    "pxl_row_in_fullres", "pxl_col_in_fullres",
]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def total_umi_per_spot(outs_dir: Path) -> pd.DataFrame:
    matrix_dir = outs_dir / "filtered_feature_bc_matrix"
    barcode_path = matrix_dir / "barcodes.tsv.gz"
    if not barcode_path.is_file():
        barcode_path = matrix_dir / "barcodes.tsv"
    matrix_path = matrix_dir / "matrix.mtx.gz"
    if not matrix_path.is_file():
        matrix_path = matrix_dir / "matrix.mtx"
    if not barcode_path.is_file() or not matrix_path.is_file():
        raise FileNotFoundError(f"Missing filtered matrix input under {matrix_dir}")
    opener = gzip.open if barcode_path.suffix == ".gz" else open
    with opener(barcode_path, "rt") as handle:
        barcodes = [line.strip() for line in handle if line.strip()]
    totals = np.asarray(mmread(matrix_path).tocsc().sum(axis=0)).ravel().astype(np.int64)
    if len(barcodes) != len(totals):
        raise ValueError(f"Barcode/matrix mismatch in {matrix_dir}")
    return pd.DataFrame({"barcode": barcodes, "total_umi": totals})


def viewer_config_hg19(study_name: str) -> str:
    return f"""# SPARCALViewer study generated by the CalicoST evidence ablation
project: SPARCAL
study: {study_name}
genome: hg19

files:
  snv_matrix: snv_matrix.pkl
  tissue_positions: tissue_positions.csv
  hires_image: tissue_hires_image.png
  scalefactors: scalefactors_json.json
  tumor_groups: tumor_groups.csv
  variant_groups: variant_groups.csv
  tumor_centers: tumor_centers.csv
  spot_coverage: spot_coverage.csv

image:
  x_column: pxl_col_in_fullres
  y_column: pxl_row_in_fullres
  scalef_key: tissue_hires_scalef
  spot_diameter_key: spot_diameter_fullres
  in_tissue_only: true

variant_grouping:
  general_min_fraction: 80
  exclusive_inside_min: 80
  exclusive_outside_max: 20
"""


def spatial_inputs(cohort: str, section: str) -> Dict[str, Path]:
    outs = (
        STMUT_ROOT / f"{cohort}_Visium" / f"spaceranger_align_rep{section}_hg19"
        / f"{cohort}_Tumor_output" / "outs"
    )
    spatial = outs / "spatial"
    return {
        "outs": outs,
        "tissue_positions.csv": spatial / "tissue_positions.csv",
        "tissue_hires_image.png": spatial / "tissue_hires_image.png",
        "scalefactors_json.json": spatial / "scalefactors_json.json",
    }


def normalize_positions(source: Path, destination: Path) -> None:
    with source.open() as handle:
        first_line = handle.readline().strip()
    if first_line.startswith("barcode,"):
        frame = pd.read_csv(source)
    else:
        frame = pd.read_csv(source, header=None, names=POSITION_COLUMNS)
    missing = set(POSITION_COLUMNS) - set(frame.columns)
    if missing:
        raise ValueError(f"Missing position columns in {source}: {sorted(missing)}")
    frame[POSITION_COLUMNS].to_csv(destination, index=False)


def empty_profile_tables(package_dir: Path) -> None:
    pd.DataFrame(columns=["profile", "region_name", "barcode"]).to_csv(
        package_dir / "tumor_groups.csv", index=False
    )
    pd.DataFrame(
        columns=["profile", "region_name", "group_name", "group_type", "snv_key"]
    ).to_csv(package_dir / "variant_groups.csv", index=False)
    pd.DataFrame(columns=["profile", "region_name", "barcode"]).to_csv(
        package_dir / "tumor_centers.csv", index=False
    )


def build_one(
    cohort: str,
    section: str,
    mode: str,
    output_root: Path,
    coverage: pd.DataFrame,
) -> Dict[str, object]:
    mode_info = MODES[mode]
    study_name = f"{cohort}_rep{section}_SPARCAL_somatic_{mode}"
    calicost_purity_informative = not (cohort == "P4" and section == "2")
    voting_features = (
        ["delta", "epsilon", "zeta", "theta"]
        if mode == "full_calicost" and calicost_purity_informative
        else (["zeta", "theta"] if mode == "full_calicost" else ["zeta"])
    )
    section_root = PROJECT_ROOT / "data" / f"{cohort}_tumor" / section
    matrix_path = (
        section_root / "matrix"
        / f"{cohort}_TUMOR_{section}_{mode_info['model']}_somatic_matrix.pkl"
    )
    spatial = spatial_inputs(cohort, section)
    required = [matrix_path, spatial["tissue_positions.csv"],
                spatial["tissue_hires_image.png"], spatial["scalefactors_json.json"]]
    missing = [str(item) for item in required if not item.is_file()]
    if missing:
        raise FileNotFoundError("Missing viewer input(s):\n  " + "\n  ".join(missing))

    package_dir = output_root / study_name
    package_dir.mkdir(parents=True, exist_ok=True)

    matrix = pd.read_pickle(matrix_path)
    if matrix.empty:
        raise ValueError(f"Empty somatic matrix: {matrix_path}")
    matrix = (matrix > 0).astype(np.uint8)
    matrix.index = matrix.index.astype(str)
    matrix.columns = matrix.columns.astype(str)
    matrix.to_pickle(package_dir / "snv_matrix.pkl")

    normalize_positions(
        spatial["tissue_positions.csv"], package_dir / "tissue_positions.csv"
    )
    for filename in ("tissue_hires_image.png", "scalefactors_json.json"):
        shutil.copy2(spatial[filename], package_dir / filename)
    coverage.to_csv(package_dir / "spot_coverage.csv", index=False)
    empty_profile_tables(package_dir)
    (package_dir / f"{study_name}.config").write_text(viewer_config_hg19(study_name))

    manifest = {
        "study": study_name,
        "cohort": cohort,
        "replicate": int(section),
        "matrix_class": "somatic",
        "evidence_mode": mode,
        "voting_features": voting_features,
        "calicost_purity_informative": calicost_purity_informative,
        "description": mode_info["description"],
        "matrix_source": str(matrix_path.relative_to(PROJECT_ROOT)),
        "matrix_shape": [int(matrix.shape[0]), int(matrix.shape[1])],
        "matrix_dtype": str(matrix.dtypes.iloc[0]),
        "spatial_reference": "hg19 Space Ranger output",
        "tumor_profiles": (
            "empty by design; create Auto regions interactively, then compare "
            "full and ablation downstream using the supplied study pair"
        ),
    }
    (package_dir / "MANIFEST.json").write_text(json.dumps(manifest, indent=2) + "\n")

    archive = output_root / f"{study_name}.zip"
    package_files = [
        package_dir / "snv_matrix.pkl",
        package_dir / "tissue_positions.csv",
        package_dir / "tissue_hires_image.png",
        package_dir / "scalefactors_json.json",
        package_dir / "spot_coverage.csv",
        package_dir / "tumor_groups.csv",
        package_dir / "variant_groups.csv",
        package_dir / "tumor_centers.csv",
        package_dir / f"{study_name}.config",
        package_dir / "MANIFEST.json",
    ]
    with zipfile.ZipFile(
        archive, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6
    ) as handle:
        for item in package_files:
            handle.write(item, arcname=f"{study_name}/{item.name}")

    return {
        "study": study_name,
        "cohort": cohort,
        "replicate": int(section),
        "matrix_class": "somatic",
        "evidence_mode": mode,
        "voting_features": ",".join(voting_features),
        "calicost_purity_informative": calicost_purity_informative,
        "spots": int(matrix.shape[0]),
        "snvs": int(matrix.shape[1]),
        "archive": archive.name,
        "archive_bytes": archive.stat().st_size,
        "archive_sha256": sha256(archive),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-root", type=Path,
        default=VIEWER_ROOT / "dist" / "studies" / "p4p6_calicost_ablation_20260907",
    )
    parser.add_argument(
        "--manifest-output", type=Path,
        default=VIEWER_ROOT / "study_manifests" / "P4P6_calicost_ablation_20260907.tsv",
    )
    args = parser.parse_args()
    args.output_root.mkdir(parents=True, exist_ok=True)

    results: List[Dict[str, object]] = []
    for cohort, section in SAMPLES:
        spatial = spatial_inputs(cohort, section)
        coverage = total_umi_per_spot(spatial["outs"])
        for mode in MODES:
            print(f"Building {cohort} rep{section} {mode}...", flush=True)
            results.append(
                build_one(cohort, section, mode, args.output_root, coverage)
            )

    manifest = pd.DataFrame(results)
    local_manifest = args.output_root / "P4P6_calicost_ablation_20260907.tsv"
    manifest.to_csv(local_manifest, sep="\t", index=False)
    args.manifest_output.parent.mkdir(parents=True, exist_ok=True)
    manifest.to_csv(args.manifest_output, sep="\t", index=False)
    print(f"Built {len(results)} distinct viewer studies")
    print(f"Release assets: {args.output_root}")
    print(f"Tracked manifest: {args.manifest_output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
