[DEFAULT]
THRESHOLD = 1
FILTER = filter_by_neighbor
SNV_TOOL = self
NUM_CLUSTER = 5
NEIGHBOR_LIM = 0
RAD_LIM = 330
SPATIALID = breast_cancer
REFERENCE = /data/maiziezhou_lab/Softwares/GRCh38-3.0.0/fasta/genome.fa
BEDFILE=/data/maiziezhou_lab/hanliu/projects/snv_calling/data/reference/GRCh38.bed
HEADER=/data/maiziezhou_lab/hanliu/projects/snv_calling/data/reference/header.txt
SH_PATH = /data/maiziezhou_lab/hanliu/projects/snv_calling
LOCAL_DATA_PATH = /data/maiziezhou_lab/hanliu/projects/snv_calling/data/${data_name}/
MAIZIE_PATH = /data/maiziezhou_lab/Datasets/ST_datasets/10x_BC_6.5mm_Visium_CytAssist_FFPE
; GOLD_CLUSTER = /data/maiziezhou_lab/Datasets/ST_datasets/
RESULT = ${LOCAL_DATA_PATH}/results/${SNV_TOOL}_${NEIGHBOR_LIM}_${FILTER}

[INPUT]
TISSUE_POS_PATH = ${MAIZIE_PATH}/spatial/tissue_positions.csv
BAM_PATH = ${MAIZIE_PATH}/bam_bycell

[PROCESS]
NEIGHBOR_PIXEL_PATH = ${LOCAL_DATA_PATH}/${NEIGHBOR_LIM}.csv
MERGED_BAM_PATH = /data/maiziezhou_lab/Datasets/ST_datasets/10x_BC_6.5mm_Visium_CytAssist_FFPE/split_by_cell/BAMs
OUT_VCF_PATH = ${LOCAL_DATA_PATH}/output_VCFs/${SNV_TOOL}_${NEIGHBOR_LIM}_unfiltered
VCF_TABLES_PATH = ${LOCAL_DATA_PATH}/processed_data/vcf_tables/${SNV_TOOL}_${NEIGHBOR_LIM}_${FILTER}
PROCESSED_VCF_TABLES_PATH = ${LOCAL_DATA_PATH}/processed_data/processed_vcf_tables/${SNV_TOOL}_${NEIGHBOR_LIM}_${FILTER}

[RESULT]
UNION_SET_PATH = ${RESULT}_union_set.csv
MATRIX_PATH = ${RESULT}_matrix.pkl
MODIFIED_MATRIX_PATH = ${RESULT}_all_inTissue_matrix.pkl
SUM_SNP_PATH = ${RESULT}_sum_snp.txt
HISTOGRAM_PATH = ${RESULT}_histogram.png
CLUSTER_PATH = ${RESULT}_clustering_${NUM_CLUSTER}.csv
VISUAL_PATH = ${RESULT}.png

