#!/usr/bin/env python3
"""
Plot SNV matrix and perform basic analysis.

This script loads the SNV matrix generated by generate_snv_matrix.py,
creates an AnnData object, and produces various visualizations.

Usage:
    python plot_snv_matrix.py --dataset DLPFC --section_id 151507 --filter-name filtered_by_neighbor_2
"""

import os
import argparse
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.sparse as sp
from scipy.stats import fisher_exact
import scanpy as sc
import anndata as ad
from PIL import Image
from typing import Dict, List, Optional

# Base directories
PROJECT_BASE_DIR = "/data/maiziezhou_lab/yuqi/snv_calling"
DATA_BASE_DIR = "/data/maiziezhou_lab/Datasets/ST_datasets/DLPFC12"  # Directory with gene expression data
# Updated SNV_BASE_DIR to match the structure in run_generate_matrix.py
SNV_BASE_DIR = PROJECT_BASE_DIR  # Root directory for SNV matrices

def load_snv_matrix(dataset: str, section_id: str, caller: str = "self", 
                  filter_name: str = "filtered", grouping: str = "0") -> pd.DataFrame:
    """
    Load SNV matrix from pickle file.
    
    Args:
        dataset: Dataset name (e.g., 'DLPFC')
        section_id: Section ID
        caller: Caller used for SNV data
        filter_name: Filter method used for SNV data
        grouping: Grouping strategy used for SNV data
        
    Returns:
        pandas DataFrame with the SNV matrix
    """
    # Construct file path to match structure in run_generate_matrix.py
    file_name = f"{dataset.upper()}_{section_id}_{caller}_{filter_name}_{grouping}_matrix.pkl"
    # Updated path construction to match run_generate_matrix.py output location
    file_path = os.path.join(SNV_BASE_DIR, "data", dataset.lower(), section_id, "matrix", file_name)
    
    # Check if file exists
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"SNV matrix file not found: {file_path}")
    
    # Load the DataFrame
    print(f"Loading SNV matrix from {file_path}")
    df = pd.read_pickle(file_path)
    print(f"Loaded matrix with shape {df.shape}")
    
    return df

def load_ground_truth(data_dir: str, section_id: str) -> pd.DataFrame:
    """
    Load ground truth cluster labels.
    
    Args:
        data_dir: Directory containing the gene expression data
        section_id: Section ID
        
    Returns:
        pandas DataFrame with ground truth labels
    """
    # Construct path to ground truth file
    gt_file = os.path.join(data_dir, section_id, 'gt', 'tissue_positions_list_GTs.txt')
    
    # Check if file exists
    if not os.path.exists(gt_file):
        raise FileNotFoundError(f"Ground truth file not found: {gt_file}")
    
    # Load the DataFrame
    print(f"Loading ground truth from {gt_file}")
    gt_df = pd.read_csv(gt_file, sep=',', header=None, index_col=0)
    gt_df.columns = ['in_tissue', 'array_row', 'array_col', 'pxl_col_in_fullres', 'pxl_row_in_fullres', 'original_clusters']
    gt_df['original_clusters'] = gt_df['original_clusters'].astype(int).astype(str)
    
    return gt_df

def create_anndata(snv_matrix: pd.DataFrame, gt_df: pd.DataFrame) -> ad.AnnData:
    """
    Create AnnData object from SNV matrix and ground truth.
    
    Args:
        snv_matrix: pandas DataFrame with SNV matrix
        gt_df: pandas DataFrame with ground truth labels
        
    Returns:
        AnnData object
    """
    # Find common barcodes
    common_barcodes = gt_df.index.intersection(snv_matrix.index)
    print(f"Number of common barcodes: {len(common_barcodes)}")
    
    # Subset both datasets
    gt_df = gt_df.loc[common_barcodes]
    snv_matrix = snv_matrix.loc[common_barcodes]
    
    # Create AnnData object
    adata = ad.AnnData(X=sp.csr_matrix(snv_matrix.values),
                       obs=gt_df,
                       var=pd.DataFrame(index=snv_matrix.columns))
    
    # Update var
    adata.var['snp_id'] = adata.var.index
    adata.var['feature_types'] = 'SNP'
    adata.var[['chromosome', 'position']] = adata.var['snp_id'].str.split('_', expand=True)
    
    # Update obsm
    adata.obsm['spatial'] = adata.obs[['pxl_col_in_fullres', 'pxl_row_in_fullres']].values
    
    return adata

def add_spatial_info(adata: ad.AnnData, section_id: str) -> ad.AnnData:
    """
    Add spatial information from gene expression data.
    
    Args:
        adata: AnnData object with SNV data
        section_id: Section ID
        
    Returns:
        AnnData object with spatial information
    """
    # Load spatial information from gene expression data
    try:
        ge_ad = sc.read_visium(path=os.path.join(DATA_BASE_DIR, section_id), 
                             count_file=f'{section_id}_filtered_feature_bc_matrix.h5', 
                             load_images=True)
        
        # Copy spatial information
        if 'spatial' in ge_ad.uns:
            adata.uns['spatial'] = ge_ad.uns['spatial']
            print(f"Spatial information copied for section {section_id}")
        else:
            print(f"Warning: No spatial information found in gene expression data for section {section_id}")
            
    except Exception as e:
        print(f"Warning: Error loading gene expression data: {e}")
        print("Continuing without spatial information")
    
    return adata

def plot_snv_heatmap(adata: ad.AnnData, section_id: str, output_dir: str = None):
    """
    Plot heatmap of SNV data, sorted by cluster.
    
    Args:
        adata: AnnData object with SNV data
        section_id: Section ID
        output_dir: Directory to save output plots (default: current directory)
    """
    # Create output directory if specified
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    
    # Convert cluster labels to integers
    adata.obs['original_clusters'] = adata.obs['original_clusters'].astype(int)
    
    # Sort spots by their cluster
    adata_sorted = adata[adata.obs.sort_values('original_clusters').index]
    
    # Convert sparse matrix to dense if necessary
    if sp.issparse(adata_sorted.X):
        snv_matrix = adata_sorted.X.todense()
    else:
        snv_matrix = adata_sorted.X
    
    # Plot overall heatmap for spots*snv
    plt.figure(figsize=(20, 10))
    sns.heatmap(snv_matrix, cmap='YlOrRd', yticklabels=False)
    plt.title(f'Overall SNV Heatmap for Section {section_id}')
    plt.xlabel('All SNVs')
    plt.ylabel('Spots (sorted by cluster)')
    
    # Add cluster separation lines
    cluster_labels = adata_sorted.obs['original_clusters'].values
    cluster_changes = np.where(np.diff(cluster_labels.astype(int)) != 0)[0]
    print(f"Cluster changes at rows: {cluster_changes}")
    for change in cluster_changes:
        plt.axhline(y=change, color='black', linewidth=1)
    
    # Annotate cluster numbers
    unique_clusters = np.unique(cluster_labels)
    cluster_starts = np.concatenate([[0], cluster_changes + 1])
    
    for i, cluster in enumerate(unique_clusters):
        start = cluster_starts[i]
        end = cluster_changes[i] if i < len(cluster_changes) else snv_matrix.shape[0]
        midpoint = (start + end) / 2
        plt.text(-0.01 * snv_matrix.shape[1], midpoint, f'Cluster {cluster}', 
                 verticalalignment='center', horizontalalignment='right')
    
    plt.tight_layout()
    
    # Save if output directory specified
    if output_dir:
        plt.savefig(os.path.join(output_dir, f'{section_id}_snv_heatmap.png'), dpi=300, bbox_inches='tight')
    else:
        plt.show()
    
    plt.close()

def plot_spatial(adata: ad.AnnData, section_id: str, output_dir: str = None):
    """
    Plot spatial distribution of SNVs and clusters.
    
    Args:
        adata: AnnData object with SNV data
        section_id: Section ID
        output_dir: Directory to save output plots (default: current directory)
    """
    # Create output directory if specified
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    
    try:
        # Plot clusters
        sc.pl.spatial(adata, color='original_clusters', spot_size=30, 
                    title=f'Cluster Annotation - Section {section_id}')
        
        # Save if output directory specified
        if output_dir:
            plt.savefig(os.path.join(output_dir, f'{section_id}_spatial_clusters.png'), dpi=300, bbox_inches='tight')
        
        # Plot SNV count per spot
        snv_count = np.array(adata.X.sum(axis=1)).flatten()
        adata.obs['snv_count'] = snv_count
        
        sc.pl.spatial(adata, color='snv_count', spot_size=30, 
                    title=f'SNV Count per Spot - Section {section_id}')
        
        # Save if output directory specified
        if output_dir:
            plt.savefig(os.path.join(output_dir, f'{section_id}_spatial_snv_count.png'), dpi=300, bbox_inches='tight')
        
        plt.close()
    except Exception as e:
        print(f"Warning: Error plotting spatial data: {e}")
        print("Continuing without spatial plots")

def find_cluster_specific_snvs(adata: ad.AnnData, section_id: str, output_dir: str = None, 
                              min_odds_ratio: float = 2.0, max_pval: float = 0.05):
    """
    Find SNVs that are specific to particular clusters.
    
    Args:
        adata: AnnData object with SNV data
        section_id: Section ID
        output_dir: Directory to save output (default: current directory)
        min_odds_ratio: Minimum odds ratio to consider an SNV specific to a cluster
        max_pval: Maximum p-value to consider an SNV significantly associated with a cluster
    """
    # Create output directory if specified
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    
    # Convert to dense matrix if necessary
    if sp.issparse(adata.X):
        X = adata.X.todense()
    else:
        X = adata.X
    
    # Get cluster information
    clusters = adata.obs['original_clusters'].astype(int).values
    unique_clusters = np.unique(clusters)
    
    # Store results
    results = []
    
    # For each SNV, test association with each cluster
    for snv_idx in tqdm(range(adata.shape[1])):
        snv_id = adata.var.index[snv_idx]
        snv_values = np.array(X[:, snv_idx]).flatten()
        
        for cluster in unique_clusters:
            # Create 2x2 contingency table
            # [spots with SNV in cluster, spots with SNV not in cluster]
            # [spots without SNV in cluster, spots without SNV not in cluster]
            in_cluster = (clusters == cluster)
            has_snv = (snv_values > 0)
            
            a = np.sum(has_snv & in_cluster)  # In cluster, has SNV
            b = np.sum(has_snv & ~in_cluster)  # Not in cluster, has SNV
            c = np.sum(~has_snv & in_cluster)  # In cluster, no SNV
            d = np.sum(~has_snv & ~in_cluster)  # Not in cluster, no SNV
            
            # Skip if no occurrence of SNV in this cluster
            if a == 0:
                continue
            
            # Perform Fisher's exact test
            table = [[a, b], [c, d]]
            odds_ratio, pval = fisher_exact(table)
            
            # Store result if significant
            if odds_ratio >= min_odds_ratio and pval <= max_pval:
                results.append({
                    'snv_id': snv_id,
                    'cluster': cluster,
                    'odds_ratio': odds_ratio,
                    'pval': pval,
                    'count_in_cluster': a,
                    'count_not_in_cluster': b
                })
    
    # Convert to DataFrame and sort
    if results:
        df_results = pd.DataFrame(results)
        df_results = df_results.sort_values(['cluster', 'odds_ratio'], ascending=[True, False])
        
        # Save if output directory specified
        if output_dir:
            output_file = os.path.join(output_dir, f'{section_id}_cluster_specific_snvs.csv')
            df_results.to_csv(output_file, index=False)
            print(f"Cluster-specific SNVs saved to {output_file}")
        
        # Show top SNVs per cluster
        for cluster in unique_clusters:
            cluster_results = df_results[df_results['cluster'] == cluster]
            if not cluster_results.empty:
                print(f"\nTop SNVs for Cluster {cluster}:")
                print(cluster_results.head(5))
        
        return df_results
    else:
        print("No cluster-specific SNVs found")
        return None

def save_anndata(adata: ad.AnnData, section_id: str, filter_name: str, output_dir: str):
    """
    Save AnnData object to h5ad file.
    
    Args:
        adata: AnnData object to save
        section_id: Section ID
        filter_name: Filter method used for SNV data
        output_dir: Directory to save output
    """
    # Create output directory if necessary
    os.makedirs(output_dir, exist_ok=True)
    
    # Construct file path
    file_path = os.path.join(output_dir, f'{section_id}_{filter_name}_snv.h5ad')
    
    # Save AnnData object
    print(f"Saving AnnData object to {file_path}")
    adata.write(file_path)
    print("Done!")
    
    return file_path

def main():
    parser = argparse.ArgumentParser(description="Plot and analyze SNV matrix")
    
    # Required arguments
    parser.add_argument("--dataset", required=True, 
                      help="Dataset name (e.g., 'DLPFC', 'P4_TUMOR')")
    parser.add_argument("--section_id", required=True,
                      help="Section ID (e.g., '151507' for DLPFC)")
    
    # Optional arguments
    parser.add_argument("--caller", default="self",
                      help="Name of the variant caller (default: self)")
    parser.add_argument("--filter-name", default="filtered",
                      help="Name of the filter in the input file (default: filtered)")
    parser.add_argument("--grouping", default="0",
                      help="Grouping strategy (default: 0)")
    parser.add_argument("--output-dir", 
                      help="Directory to save output (default: current directory)")
    parser.add_argument("--find-cluster-snvs", action="store_true",
                      help="Find cluster-specific SNVs")
    parser.add_argument("--save-anndata", action="store_true",
                      help="Save AnnData object to h5ad file")
    
    args = parser.parse_args()
    
    # Override DATA_BASE_DIR and SNV_BASE_DIR if needed (add as arguments if necessary)
    
    # Load SNV matrix
    snv_matrix = load_snv_matrix(
        args.dataset,
        args.section_id,
        args.caller,
        args.filter_name,
        args.grouping
    )
    
    # Load ground truth
    gt_df = load_ground_truth(DATA_BASE_DIR, args.section_id)
    
    # Create AnnData object
    adata = create_anndata(snv_matrix, gt_df)
    
    # Add spatial information
    adata = add_spatial_info(adata, args.section_id)
    
    # Plot SNV heatmap
    plot_snv_heatmap(adata, args.section_id, args.output_dir)
    
    # Plot spatial visualization
    plot_spatial(adata, args.section_id, args.output_dir)
    
    # Find cluster-specific SNVs if requested
    if args.find_cluster_snvs:
        cluster_snvs = find_cluster_specific_snvs(adata, args.section_id, args.output_dir)
    
    # Save AnnData object if requested
    if args.save_anndata and args.output_dir:
        save_anndata(adata, args.section_id, args.filter_name, args.output_dir)
    
    # Print summary
    print("\nSummary:")
    print(f"  Dataset: {args.dataset}")
    print(f"  Section ID: {args.section_id}")
    print(f"  Filter: {args.filter_name}")
    print(f"  Number of spots: {adata.shape[0]}")
    print(f"  Number of SNVs: {adata.shape[1]}")
    print(f"  Number of clusters: {adata.obs['original_clusters'].nunique()}")
    print(f"  Average SNVs per spot: {adata.X.sum() / adata.shape[0]:.2f}")
    
    # Show most common SNVs
    if sp.issparse(adata.X):
        snv_sums = np.asarray(adata.X.sum(axis=0)).flatten()
    else:
        snv_sums = np.sum(adata.X, axis=0)
    
    most_common_indices = np.argsort(snv_sums)[-5:][::-1]
    print("\nMost common SNVs:")
    for idx in most_common_indices:
        print(f"  {adata.var.index[idx]}: {snv_sums[idx]} spots")

if __name__ == "__main__":
    from tqdm import tqdm
    main()

# Usage examples:
# Last step we call the script: python scripts/6_spatial_filter/run_generate_matrix.py --dataset dlpfc --section_id 151507 --quality-filter baseQ0mapQ0 --filter-name group_by_6
# Now we need to call:
# python scripts/6_spatial_filter/plot_snv_matrix.py --dataset dlpfc --section_id 151507 --filter-name group_by_6