# The idea of this script is to analyze the VCF files generated by Beagle by comparing the input and output variants.
# The script will calculate the number of variants, SNPs, and indels in each chromosome before and after Beagle processing.
# It will also calculate the ratio of output to input variants and generate visualizations to compare the statistics.
# The script will use the bcftools command-line tool to extract variant counts and statistics from the VCF files.
# The script will be run as a standalone Python script and will generate output files with the statistics and plots.
# The script will be part of the snv_calling package and will be located in the scripts/filtering directory.

import os
import subprocess
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
import numpy as np
from typing import Dict, List, Tuple

class VCFAnalyzer:
    def __init__(self, project_dir: str, section_id: str):
        self.project_dir = project_dir
        self.section_id = section_id
        self.input_dir = os.path.join(project_dir, "data/dlpfc", section_id, 
                                    "output_VCFs/mpileup_multi_bam")
        self.output_dir = os.path.join(project_dir, "data/dlpfc", section_id, 
                                     "output_VCFs/beagle")
        self.stats_dir = os.path.join(project_dir, "data/dlpfc", section_id, 
                                    "metrics/beagle")
        Path(self.stats_dir).mkdir(parents=True, exist_ok=True)
        
    def setup_environment(self):
        """Setup bcftools environment"""
        bcftools_path = "/data/maiziezhou_lab/yuqi/snv_calling/apps"
        os.environ['PATH'] = f"{bcftools_path}:{os.environ.get('PATH', '')}"
        os.environ['LD_LIBRARY_PATH'] = f"{bcftools_path}:{os.environ.get('LD_LIBRARY_PATH', '')}"

    def get_variant_counts(self, vcf_path: str, chrom: str = None) -> int:
        """Get variant count for a VCF file"""
        if not os.path.exists(vcf_path):
            print(f"File not found: {vcf_path}")
            return 0
            
        if chrom:
            cmd = f"bcftools view -r {chrom} {vcf_path} | bcftools view -H | wc -l"
        else:
            cmd = f"bcftools view -H {vcf_path} | wc -l"
            
        try:
            output = subprocess.check_output(cmd, shell=True)
            return int(output.strip())
        except subprocess.CalledProcessError as e:
            print(f"Error running command '{cmd}': {e}")
            return 0

    def get_vcf_stats(self, vcf_path: str) -> Dict:
        """Get VCF statistics using bcftools stats"""
        if not os.path.exists(vcf_path):
            print(f"File not found: {vcf_path}")
            return {}
            
        try:
            cmd = f"bcftools stats {vcf_path}"
            output = subprocess.check_output(cmd, shell=True, text=True)
            
            stats = {}
            for line in output.split('\n'):
                if line.startswith('SN'):
                    parts = line.split('\t')
                    if len(parts) >= 3:
                        key = parts[2].split(':')[0].strip()
                        try:
                            value = int(parts[3])
                            stats[key] = value
                        except (ValueError, IndexError):
                            continue
            return stats
        except subprocess.CalledProcessError as e:
            print(f"Error running bcftools stats on {vcf_path}: {e}")
            return {}

    def analyze_chromosomes(self) -> pd.DataFrame:
        """Analyze all chromosomes and return statistics"""
        self.setup_environment()
        chromosomes = [f"chr{i}" for i in range(1, 23)]
        results = []
        
        input_vcf = os.path.join(self.input_dir, "merged_multi_bam.chr.vcf.gz")
        
        for chrom in chromosomes:
            print(f"Processing {chrom}...")
            output_vcf = os.path.join(self.output_dir, f"{chrom}.vcf.gz")
            
            # Verify files exist
            if not os.path.exists(input_vcf):
                print(f"Input VCF not found: {input_vcf}")
                continue
            if not os.path.exists(output_vcf):
                print(f"Output VCF not found: {output_vcf}")
                continue
                
            # Get counts and stats
            input_count = self.get_variant_counts(input_vcf, chrom)
            output_count = self.get_variant_counts(output_vcf)
            
            input_stats = self.get_vcf_stats(input_vcf)
            output_stats = self.get_vcf_stats(output_vcf)
            
            results.append({
                'chromosome': chrom,
                'input_variants': input_count,
                'output_variants': output_count,
                'ratio': output_count/input_count if input_count else 0,
                'input_snps': input_stats.get('number of SNPs', 0),
                'output_snps': output_stats.get('number of SNPs', 0),
                'input_indels': input_stats.get('number of indels', 0),
                'output_indels': output_stats.get('number of indels', 0)
            })
            
        return pd.DataFrame(results)

# Previous imports remain the same, add:
    plt.style.use('default')  # Use default matplotlib style instead

# Rest of the code remains the same but change the plot_statistics method:
    def plot_statistics(self, df: pd.DataFrame):
        """Create visualizations of the statistics"""
        if df.empty:
            print("No data to plot")
            return
            
        # Use basic matplotlib style
        plt.rcParams['figure.figsize'] = [15, 6]
        plt.rcParams['axes.grid'] = True
        
        # 1. Variant counts comparison
        plt.figure()
        x = np.arange(len(df['chromosome']))
        width = 0.35
        
        plt.bar(x - width/2, df['input_variants'], width, label='Input variants', color='skyblue')
        plt.bar(x + width/2, df['output_variants'], width, label='Output variants', color='lightcoral')
        
        plt.xlabel('Chromosome')
        plt.ylabel('Number of variants')
        plt.title('Comparison of variant counts before and after Beagle processing')
        plt.xticks(x, df['chromosome'], rotation=45)
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(self.stats_dir, 'variant_counts.png'))
        plt.close()
        
        # 2. SNPs vs Indels
        plt.figure()
        colors = ['skyblue', 'lightcoral', 'lightgreen', 'orange']
        df_melted = pd.melt(df, 
                        id_vars=['chromosome'],
                        value_vars=['input_snps', 'output_snps', 
                                    'input_indels', 'output_indels'],
                        var_name='Type', value_name='Count')
        
        positions = np.arange(len(df['chromosome']))
        width = 0.2
        
        for i, var_type in enumerate(['input_snps', 'output_snps', 'input_indels', 'output_indels']):
            data = df_melted[df_melted['Type'] == var_type]['Count']
            plt.bar(positions + (i-1.5)*width, data, width, label=var_type, color=colors[i])
        
        plt.xlabel('Chromosome')
        plt.ylabel('Count')
        plt.title('Distribution of SNPs and Indels across chromosomes')
        plt.xticks(positions, df['chromosome'], rotation=45)
        plt.legend()
        plt.tight_layout()
        plt.savefig(os.path.join(self.stats_dir, 'snps_indels.png'))
        plt.close()
        
        # 3. Ratio plot
        plt.figure()
        plt.plot(df['chromosome'], df['ratio'], marker='o', color='blue')
        plt.axhline(y=1, color='red', linestyle='--', alpha=0.5)
        plt.xlabel('Chromosome')
        plt.ylabel('Output/Input ratio')
        plt.title('Ratio of output to input variants')
        plt.xticks(rotation=45)
        plt.grid(True)
        plt.tight_layout()
        plt.savefig(os.path.join(self.stats_dir, 'variant_ratio.png'))
        plt.close()
        
        # Save statistics to CSV
        df.to_csv(os.path.join(self.stats_dir, 'vcf_statistics.csv'), index=False)

def main():
    analyzer = VCFAnalyzer("/data/maiziezhou_lab/yuqi/snv_calling", "151507")
    
    print("Starting VCF analysis...")
    stats_df = analyzer.analyze_chromosomes()
    
    if not stats_df.empty:
        print("\nGenerating plots...")
        analyzer.plot_statistics(stats_df)
        
        print("\nSummary Statistics:")
        print("-" * 50)
        print(f"Total input variants: {stats_df['input_variants'].sum():,}")
        print(f"Total output variants: {stats_df['output_variants'].sum():,}")
        print(f"Average input/output ratio: {stats_df['ratio'].mean():.2f}")
        print(f"Total input SNPs: {stats_df['input_snps'].sum():,}")
        print(f"Total output SNPs: {stats_df['output_snps'].sum():,}")
        print(f"Total input indels: {stats_df['input_indels'].sum():,}")
        print(f"Total output indels: {stats_df['output_indels'].sum():,}")
    else:
        print("No data was processed. Check the error messages above.")

if __name__ == "__main__":
    main()